# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'XNQBannerView' do

pod 'SDWebImage'

end

target 'XNQBannerViewTests' do

end

target 'XNQBannerViewUITests' do

end

